// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI3mFOwS5ad8Iyz-uk-_QPjua_wtcvQpg',
    appId: '1:1056116937101:web:a7474bc22a44ef4b14adc4',
    messagingSenderId: '1056116937101',
    projectId: 'leisure-boat-controller',
    authDomain: 'leisure-boat-controller.firebaseapp.com',
    storageBucket: 'leisure-boat-controller.appspot.com',
    measurementId: 'G-47QSKX8C7B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClUXtWb8H5KMhdFXWHgg6y4v4jywP669Y',
    appId: '1:1056116937101:android:66e9caf4e795a96714adc4',
    messagingSenderId: '1056116937101',
    projectId: 'leisure-boat-controller',
    storageBucket: 'leisure-boat-controller.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1T-XCTA9cUqDhcfuzZw9_yKOjW5-xapA',
    appId: '1:1056116937101:ios:1140a5f1370fa3bb14adc4',
    messagingSenderId: '1056116937101',
    projectId: 'leisure-boat-controller',
    storageBucket: 'leisure-boat-controller.appspot.com',
    iosClientId: '1056116937101-o3j24utfd3u1ojlgh2m11seqplj0fshg.apps.googleusercontent.com',
    iosBundleId: 'com.example.leisureBoat',
  );
}
